### ISSUE TITLE
Take advangate of resty.core, and an init file

### ISSUE THREAD

**Issue by bungle** [kronometrix/auth#20]
I propose to add this line to nginx.conf:

```
init_by_lua_file "../app/init.lua"
```

Just before line (https://github.com/kronometrix/auth/blob/master/config/freebsd/nginx.conf.maas#L31):

```
init_worker_by_lua_file "../app/timer.lua";
```

`resty.core` is faster and better JIT compiles. Also there may be need for other init code as well.

(Same for Linux version as well)

**Comment by sparvu** [comment]
fixed for auth:

        lua_shared_dict timer_locks 1m;
        init_by_lua_file "../app/init.lua";
        init_worker_by_lua_file "../app/timer.lua";
